distributed:
    version: 2
  
    dashboard:
      link: https://cmsaf-jh.unl.edu/user/{JUPYTERHUB_USER}/proxy/{port}/status
  
    scheduler:
      idle-timeout: 3600s
  
  # uncomment to force new worker pods after 2 hrs
  #  worker:
  #    lifetime:
  #      duration: "2 hours"
  #      stagger: "10 s"
  #      restart: true
  
    admin:
      tick:
        limit: 5s
  
    logging:
      distributed: info
      bokeh: critical
      tornado: critical
      tornado.application: error

# Specific to each hub
#gateway:
  #  address: xxxx/services/dask-gateway/
  #  proxy-address: tls://xx.xxx.xx:8786
  
labextension:
  factory:
    module: 'dask_jobqueue'
    class: 'HTCondorCluster'
    args: []
    kwargs: {cores: 4,
              memory: "6GB",
              log_directory: "logs",
              silence_logs: "DEBUG",
              scheduler_options: {"dashboard_address": 8786,"port": 8787, "external_address": "{HOST_IP}:8787"},
              job_extra: {"universe": "docker",
                                     "encrypt_input_files": "/etc/cmsaf-secrets/xcache_token",
                                     "docker_image": "coffeateam/coffea-casa-analysis:0.1.45", 
                                     "container_service_names": "dask",
                                     "dask_container_port": "8787",
                                     "should_transfer_files": "YES",
                                     "when_to_transfer_output": "ON_EXIT",
                                     "+DaskSchedulerAddress": '"{HOST_IP}:8787"'}}
    default:
      workers: 5
      adapt:
        minimum: 5
        maximum: 25
    #initial: []
    #- name: "UNL HTCondor cluster"
    #  workers: 1
    #  adapt:
    #    minimum: 5
    #    maximum: 25
  