labextension:
  factory:
    module: 'coffea_casa'
    class: 'CoffeaCasaCluster'
    args: []
    kwargs: {}

    default:
      workers: 1
      adapt:
        minimum: 1
        maximum: 10

    initial:
    - name: "UNL HTCondor cluster"
      workers: 1
      adapt:
        minimum: 5
        maximum: 10
