labextension:
  factory:
    module: 'dask_jobqueue'
    # FIXME: add here CoffeaCassCluster
    class: 'HTCondorCluster'
    args: []
    kwargs: {}

    default:
      workers: null
      adapt:
        minimum: 1
        maximum: 10
    initial: []
    #- name: "UNL HTCondor cluster"
    #  workers: 1
    #  adapt:
    #    minimum: 1
    #    maximum: 10

