labextension:
  factory:
    module: 'dask_jobqueue'
    class: 'HTCondorCluster'
    args: []
    kwargs: {}
  initial:
    - name: "default"
      workers: 1
      adapt:
        minimum: 1
        maximum: 5

