labextension:
  factory:
    module: 'coffea_casa'
    class: 'CoffeaCasaCluster'
    args: []
    kwargs: {}

  default:
    workers: null
    adapt:
      minimum: 5
      maximum: 10

  initial:
  - name: "UNL HTCondor Cluster"
    workers: null
    adapt:
      minimum: 5
      maximum: 10
