# Re-tag staging SHA-tagged image with git tag and 'latest'
# tags can be anything, but typically calver string (2020.06.10)
name: Docker Publish

on:
  push:
    tags:
      - '*'

env:
  DOCKER_ORG: coffeateam
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}


jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [coffea-casa, coffea-casa-analysis]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Job Environment Variables
      run: |
        TAG="${GITHUB_REF##*/}"
        echo "TAG=${TAG}" >> $GITHUB_ENV

    - name: Authenticate with DockerHub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=$DOCKER_ORG/${{ matrix.IMAGE }}
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag temp-image $IMAGE_ID:$TAG
        docker push $IMAGE_ID:$TAG
        docker tag temp-image $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
        echo "image_tag=$IMAGE_ID:$TAG" >> $GITHUB_ENV